"""init

Revision ID: 7f002a1f2efa
Revises: 
Create Date: 2026-07-12 23:34:33.572017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f002a1f2efa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='连接名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='sqlite | redshift'),
    sa.Column('config', sa.Text(), nullable=False, comment='JSON 连接配置'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='任务名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='sql | python'),
    sa.Column('content', sa.Text(), nullable=False, comment='SQL 或 Python 代码'),
    sa.Column('connection_id', sa.Integer(), nullable=True, comment='关联连接 ID，SQL 任务必填'),
    sa.Column('output_path', sa.String(length=1024), nullable=True, comment='CSV 导出路径'),
    sa.Column('schedule_config', sa.Text(), nullable=True, comment='cron 表达式 JSON'),
    sa.Column('prerequisite_task_id', sa.Integer(), nullable=True, comment='前置任务 ID，运行前需成功执行'),
    sa.Column('tags', sa.String(length=1024), nullable=True, comment='逗号分隔的标签'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='running | success | failed'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_preview', sa.Text(), nullable=True, comment='JSON 预览数据'),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_runs_task_id', 'task_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_runs_task_id', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_table('tasks')
    op.drop_table('connections')
    # ### end Alembic commands ###
